export const PAGE_SIZE = 10
export const INFINITE_SCROLL_BOTTOM_MARGIN_PX = 400
export const INFINITE_SCROLL_TOP_MARGIN_PX = 64
export const STABLE_SCROLL_DELTA_THRESHOLD_PX = 1
export const INITIAL_SCROLL_TRIGGER_PX = 20
